admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fiche:
    resource: "@FicheBundle/Controller/"
    type:     annotation
    prefix:   /
    
kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor