admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fiche:
    resource: "@FicheBundle/Controller/"
    defaults:
        _locale: fr
    type:     annotation
    prefix:   /
    requirements:
        _locale: en|fr
    
kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor