# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AdminBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12
    providers:
        created:
            entity: 
                class: AdminBundle\Entity\User
                property: username
    role_hierarchy:
        ROLE_ADMINISTRATEUR: 
            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH
    firewalls:
        created:
            provider: created
            pattern: ^/admin/
            form_login:
                login_path: login_admin
                check_path: login_admin_check
                default_target_path: /admin/
                always_use_default_target_path: false
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/retrieve_by_mail$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMINISTRATEUR }