# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AdminBundle\Entity\User: 
            algorithm: bcrypt
            cost: 12
    providers:
        created:
            entity: 
                class: AdminBundle\Entity\User
                property: username
    role_hierarchy:
        ROLE_ADMINISTRATEUR: 
            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_CREATEUR
        ROLE_CREATEUR: 
            - ROLE_USER
            - ROLE_LECTEUR
        ROLE_LECTEUR: 
            - ROLE_USER
    firewalls:
        created:
            provider: created
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /checkRedirect
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login
            anonymous:    true
    access_control:
        - { path: ^/retrieve_by_mail$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checkRedirect$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home/, role: ROLE_LECTEUR }
        - { path: ^/admin/, role: ROLE_CREATEUR }
        - { path: ^/admin/denrees/, role: ROLE_ADMINISTRATEUR }
        - { path: ^/admin/unitemesure/, role: ROLE_ADMINISTRATEUR }
        - { path: ^/admin/user/, role: ROLE_ADMINISTRATEUR }
        - { path: ^/admin/logs/, role: ROLE_ADMINISTRATEUR }