<?php

namespace AdminBundle\Repository;

/**
 * CategorieDenreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieDenreeRepository extends \Doctrine\ORM\EntityRepository
{
}
