<?php

namespace AdminBundle\Repository;

/**
 * CategorieEtapeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEtapeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
