<?php

namespace AdminBundle\Repository;

/**
 * DenreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DenreeRepository extends \Doctrine\ORM\EntityRepository
{
}
