<?php

namespace AdminBundle\Repository;

/**
 * EtapeDenreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeDenreeRepository extends \Doctrine\ORM\EntityRepository
{
}
