<?php

namespace AdminBundle\Repository;

/**
 * EtapeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
