<?php

namespace AdminBundle\Repository;

/**
 * EtapeProduitLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeProduitLangRepository extends \Doctrine\ORM\EntityRepository
{
}
