<?php

namespace AdminBundle\Repository;

/**
 * EtapeTypeLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeTypeLangRepository extends \Doctrine\ORM\EntityRepository
{
}
