<?php

namespace AdminBundle\Repository;

/**
 * EtapeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
