<?php

namespace AdminBundle\Repository;

/**
 * TechniquesEtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TechniquesEtapeRepository extends \Doctrine\ORM\EntityRepository
{
}
