<?php

namespace AdminBundle\Repository;

/**
 * UniteMesureLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteMesureLangRepository extends \Doctrine\ORM\EntityRepository
{
}
